# toolchain for Cray XT/XE
set (CMAKE_SYSTEM_PROCESSOR "XT")
set_property (GLOBAL PROPERTY TARGET_SUPPORTS_SHARED_LIBS FALSE)

set (CMAKE_C_COMPILER cc)
set (CMAKE_CXX_COMPILER CC)

set (XT_FLAGS "-DCMK_CRAYXT=1 -DXT5_TOPOLOGY=1")
set (CMAKE_CXX_FLAGS "${XT_FLAGS}")
set (CMAKE_C_FLAGS "${XT_FLAGS}")

set (CMAKE_SHARED_LIBRARY_C_FLAGS "")
